/**
 * Styles for PokemonCard component
 * 
 * Note: Card styles are duplicated across size/selection variants for clarity.
 * Fluent UI makeStyles doesn't support easy style composition, so we define
 * each combination explicitly to maintain readability.
 */

import { makeStyles } from '@fluentui/react-components';

export const useStyles = makeStyles({
  cardSmall: {
    width: '40px',
    height: '30px',
    padding: '0',
    cursor: 'pointer',
    border: '1px solid var(--colorNeutralStroke1)',
    boxShadow: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  cardSmallSelected: {
    width: '40px',
    height: '30px',
    padding: '0',
    cursor: 'pointer',
    border: '2px solid var(--colorBrandBackground)',
    boxShadow: '0 0 4px var(--colorBrandBackground)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  cardMedium: {
    width: '60px',
    height: '45px',
    padding: '0',
    cursor: 'pointer',
    border: '1px solid var(--colorNeutralStroke1)',
    boxShadow: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  cardMediumSelected: {
    width: '60px',
    height: '45px',
    padding: '0',
    cursor: 'pointer',
    border: '2px solid var(--colorBrandBackground)',
    boxShadow: '0 0 4px var(--colorBrandBackground)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  cardSmallFainted: {
    width: '40px',
    height: '30px',
    padding: '0',
    cursor: 'pointer',
    border: '1px solid var(--colorNeutralStroke1)',
    boxShadow: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    opacity: '0.4',
    filter: 'grayscale(60%)',
  },
  cardSmallSelectedFainted: {
    width: '40px',
    height: '30px',
    padding: '0',
    cursor: 'pointer',
    border: '2px solid var(--colorBrandBackground)',
    boxShadow: '0 0 4px var(--colorBrandBackground)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    opacity: '0.4',
    filter: 'grayscale(60%)',
  },
  cardMediumFainted: {
    width: '60px',
    height: '45px',
    padding: '0',
    cursor: 'pointer',
    border: '1px solid var(--colorNeutralStroke1)',
    boxShadow: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    opacity: '0.4',
    filter: 'grayscale(60%)',
  },
  cardMediumSelectedFainted: {
    width: '60px',
    height: '45px',
    padding: '0',
    cursor: 'pointer',
    border: '2px solid var(--colorBrandBackground)',
    boxShadow: '0 0 4px var(--colorBrandBackground)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    opacity: '0.4',
    filter: 'grayscale(60%)',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
  },
});
