import { ITEMS } from "@smogon/calc";
import { gen } from "../configuration";

export function getAllAvailableItems(): string[] {
  return ITEMS[gen.num];
}

export function getPlayerAccessibleItems(): string[] {
  return [
    // Type-boosting items
    "Silk Scarf",
    "Nevermelt Ice",
    "Soft Sand",
    "Black Glasses",
    "Poison Barb",
    "Miracle Seed",
    "Silver Powder",
    "Hard Stone",
    "Sharp Beak",
    "Pixie Plate",
    "Black Belt",
    "Metal Coat",
    "Dragon Fang",
    "Charcoal",
    "Magnet",
    "Mystic Water",
    "Twisted Spoon",
    "Spell Tag",

    // Gems
    "Rock Gem",
    "Dark Gem",
    "Poison Gem",
    "Ground Gem",
    "Steel Gem",
    "Electric Gem",
    "Grass Gem",
    "Flying Gem",
    "Fire Gem",
    "Psychic Gem",
    "Bug Gem",
    "Normal Gem",
    "Ghost Gem",
    "Ice Gem",
    "Fighting Gem",
    "Water Gem",
    "Fairy Gem",
    "Dragon Gem",

    // Battle items
    "Wide Lens",
    "Muscle Band",
    "Wise Glasses",
    "Protective Pads",
    "Zoom Lens",
    "Razor Claw",
    "Razor Fang",
    "King's Rock",
    "Life Orb",
    "Metronome",
    "Shell Bell",
    "Expert Belt",
    "Assault Vest",
    "Leftovers",
    "Choice Band",
    "Choice Scarf",
    "Choice Specs",
    "Rocky Helmet",
    "Heavy Duty Boots",

    // Consumables
    "White Herb",
    "Shed Shell",
    "Electric Seed",
    "Grassy Seed",
    "Misty Seed",
    "Psychic Seed",
    "Power Herb",
    "Mental Herb",
    "Room Service",
    "Eject Button",
    "Eject Pack",
    "Red Card",
    "Focus Sash",
    // Berries
    "Oran Berry",
    "Pecha Berry",
    "Cheri Berry",
    "Chesto Berry",
    "Leppa Berry",
    "Rawst Berry",
    "Persim Berry",
    "Aspear Berry",
    "Sitrus Berry",
    "Lum Berry",
    "Lansat Berry",
    "Starf Berry",
    "Custap Berry",
    "Liechi Berry",
    "Salac Berry",
    "Petaya Berry",
    "Mago Berry",
    "Aguav Berry",
    "Iapapa Berry",
    "Ganlon Berry",
    "Apicot Berry",
    "Rowap Berry",
    "Jaboca Berry",
    "Figy Berry",
    "Wiki Berry",
    "Watmel Berry",
    "Belue Berry",
    "Pomeg Berry",
    "Kelpsy Berry",
    "Qualot Berry",
    "Hondew Berry",
    "Micle Berry",
    "Cornn Berry",
    "Durin Berry",
    "Pinap Berry",
    "Chilan Berry",
    "Occa Berry",
    "Passho Berry",
    "Wacan Berry",
    "Rindo Berry",
    "Yache Berry",
    "Chople Berry",
    "Kebia Berry",
    "Shuca Berry",
    "Coba Berry",
    "Payapa Berry",
    "Tanga Berry",
    "Charti Berry",
    "Kasib Berry",
    "Haban Berry",
    "Colbur Berry",
    "Babiri Berry",
    "Roseli Berry",
    // Mega stones
    "Absolite",
    "Aerodactylite",
    "Aggronite",
    "Alakazite",
    "Altarianite",
    "Ampharosite",
    "Audinite",
    "Banettite",
    "Beedrillite",
    "Blastoisinite",
    "Cameruptite",
    "Charizardite X",
    "Galladite",
    "Garchompite",
    "Gardevoirite",
    "Gengarite",
    "Glalitite",
    "Gyaradosite",
    "Heracronite",
    "Houndoominite",
    "Lopunnite",
    "Manectite",
    "Mawilite",
    "Medichamite",
    "Pidgeotite",
    "Pinsirite",
    "Scizorite",
    "Sharpedonite",
    "Slowbronite",
    "Steelixite",
    "Swampertite",
    "Venusaurite",
  ];
}